# Generated by Django 5.2.8 on 2026-05-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('In Route', 'In Route'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
